### ISSUE TITLE
![IMG_20230113_021826_618.jpg](https://user-images.githubusercontent.com/116040373/212429096-3f1363f9-49ff-4c82-8522-7967611dac73.jpg)

### ISSUE THREAD

**Issue by Rizalsabuga** [mdn/css-examples#103]
![IMG_20230113_021826_618.jpg](https://user-images.githubusercontent.com/116040373/212429096-3f1363f9-49ff-4c82-8522-7967611dac73.jpg)

_Originally posted by @VsubF in https://github.com/TGX-Android/Telegram-X/pull/297#pullrequestreview-1248609400_

**Comment by teoli2003** [comment]
Hi!

Please don't use this repository as a sandbox to test GitHub. It is a production repository, and each time numerous reviewers get notified.

To learn GitHub, you can create a new repository that you can delete afterward.

Thank you!
