### ISSUE TITLE
No output is showing on Web animations API

### ISSUE THREAD

**Issue by srikanth-kandi** [mdn/css-examples#145]
As you provided the link to learn about the [Web animations API frames example](https://github.com/mdn/css-examples/blob/main/animation-frames-timing-function/index-waa.html)

The file I was trying to issue on [mdn/css-examples/animation-frames-timing-function/index-waa.html](https://github.com/mdn/css-examples/blob/main/animation-frames-timing-function/index-waa.html)

I was trying to explore animations and encountered this file, which was not showing the output as expected.

It was just showing the blank screen below

![image](https://github.com/mdn/css-examples/assets/87417638/1e323e5a-d517-428b-8982-d5e243c040b2)

As I tried to figure out what the issue is about, I figured out some exceptions in the console window of the browser says

```
Uncaught TypeError: Failed to execute 'animate' on 'Element': 'frames(10)' is not a valid value for easing at 
index-waa.html:50:17
```

Attaching the console error below

![image](https://github.com/mdn/css-examples/assets/87417638/c6441ead-2796-42cc-8bfa-4c9d46ec3339)

**Comment by madhuroshan** [comment]
In the styles tag , p is given a color white and width of div is 0%, so nothing is visible even after changing styles , i cant see any animation and frames(10) is not valid it is saying, 

just change the the options object, the keyname is ```ease``` not ```easing``` 

https://github.com/mdn/css-examples/assets/95310038/fe75ff7e-d08a-4231-be53-e8b0313a11a2


```
    <style>
      body {
        margin: 0;
      }

      div {
        width: 100%;
        height: 200px;
        background: red;
      }

      p {
        color: black;
      }
    </style>
```
```
   divs[i].animate(keyFrames, {
          ease: easingFunctions[i],
          duration: 5000,
          iterations: Infinity,
   });
```

Hope this helps

**Comment by madhuroshan** [comment]
frames() is not an easing function, changed it to steps().
I have added a pull request that solves the issue.

**Comment by srikanth-kandi** [comment]
Good work @madhuroshan

**Comment by srikanth-kandi** [comment]
> frames() is not an easing function, changed it to steps(). I have added a pull request that solves the issue.

mention this issue #145 in your pull request

**Comment by madhuroshan** [comment]
you can use other easing functions like cubic-bezier , ease-in-out etc as well, have gone through mdn and cant find frames as an easing function.
