### ISSUE TITLE
Can developers edit these examples?

### ISSUE THREAD

**Issue by simevidas** [mdn/css-examples#18]
I would like to edit one of the pages in this repository to improve it. I can edit MDN via the editor interface but for the embedded examples, it seems that I have to edit them in this repository instead.

Does MDN accept pull requests from developers? There is no information about that in this repository.

**Comment by rachelandrew** [comment]
I don't see why not, but if you want to change an example please do so here before making changes on an MDN page, as otherwise the page will be different to the example.

**Comment by avivmu** [comment]
@chrisdavidmills can close
