### ISSUE TITLE
tip

### ISSUE THREAD

**Issue by xkim1994** [mdn/css-examples#24]
This example is missing the body closing  tag

**Comment by chrisdavidmills** [comment]
@xkim1994 What example? Can you give me the web address that point to the example you are talking about?

**Comment by xkim1994** [comment]
> @ xkim1994有什么例子？您能给我网址指向您正在谈论的示例吗？
https://github.com/mdn/css-examples/blob/master/css-cookbook/media-objects--download.html

**Comment by chrisdavidmills** [comment]
Thanks! I have fixed this now, and a few others that were also missing their closing `</body>` tags.
