### ISSUE TITLE
Instructions to run locally

### ISSUE THREAD

**Issue by nicoabie** [mdn/css-examples#40]
It would be nice if instructions to run it locally are provided in order to test changes and be able to contribute with solutions to the proposed exercises.

**Comment by caugner** [comment]
Most of the CSS examples in this repository contain an `index.html` that can be opened directly in the browser. 🙂

**Comment by nicoabie** [comment]
Maybe adding a comment in the readme?

**Comment by caugner** [comment]
Feel free to open a PR. 🙂
