### ISSUE TITLE
[Border-image generator] `border-image-slice` `fill` keyword not toggled in CSS output

### ISSUE THREAD

**Issue by strarsis** [mdn/css-examples#63]
Although the `border-image-slice` `fill` keyword is correctly toggled for the actual inline styles applied to the example element, 
the CSS output (that can be viewed and copied by the user) is not. `border-image-slice` always contains the `fill` keyword, 
regardless of the toggle state of the `fill` option.

**Comment by yarusome** [comment]
The `fill` value in the output CSS code is updated after following steps:

  1. The "fill" option in the "border-image-slice" section is toggled;
  2. Any input slider or dropdown menu in this section is updated, ***or*** any config button in this section is clicked (not necessarily updating values in the config panel).

---

The script uses a lot of pre-ES6 tricks, which are beyond my knowledge to fix this issue.
