### ISSUE TITLE
Superfluous `label` styling

### ISSUE THREAD

**Issue by jfrech** [mdn/css-examples#65]
The example `variable-fonts/font-weight.html` does not employ the `label` tag, yet styles it:
https://github.com/mdn/css-examples/blob/3e820cef34e6adaaf3e764d9379800fee741e435/variable-fonts/font-weight.html#L25-L29
https://github.com/mdn/css-examples/blob/3e820cef34e6adaaf3e764d9379800fee741e435/variable-fonts/font-weight.html#L53-L57

**Comment by caugner** [comment]
@jfrech Please feel free to open a PR to remove the unnecessary CSS rule.
