### ISSUE TITLE
Example is not working as expected 

### ISSUE THREAD

**Issue by ghost** [mdn/css-examples#66]
In this page [Auto-placement-in-CSS-Grid-Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout#use_cases_for_auto-placement)

By removing the property ```grid-auto-flow```, the content doesn't reflow to leave gaps as stated by the author.

More details in this other issue [#HERE](https://github.com/mdn/content/issues/13721)

> EMBED GH LIVE SAMPLE

[CSS-EXAMPLE FILE](https://github.com/mdn/css-examples/blob/main/grid/docs/autoplacement.html)
[Auto-placement-in-css-grid-layout](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/auto-placement_in_css_grid_layout/index.md)

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/css-examples/pull/143

**Comment by estelle** [comment]
should be fixed.
