### ISSUE TITLE
Variable fonts guide (`ital` axis): use a more straightforward font?

### ISSUE THREAD

**Issue by danburzo** [mdn/css-examples#88]
The particular font choice in the [Variable fonts guide: italic axis](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide#italic) seems to complicate what is [already not straightforward](https://rwt.io/typography-tips/getting-bent-current-state-italics-variable-font-support) about the `ital` axis in CSS, as `Jost-VF` uses three states: 0, 1, and 2. 

I would suggest replacing it with a font that just uses the 0 and 1 state, but I don't know what a good font for that might be. Maybe @jpamental has some ideas here?

**Comment by zfox23** [comment]
Wow, this is so fascinating! Thanks for opening up this issue, @danburzo - this is the first time I'm learning about variable fonts.

How can you tell that `Jost-VF` uses three states for the `"ital"` axis?

When I change `font-variation-settings: 'ital' 1;` to `font-variation-settings: 'ital' 2;` in the live example, I don't notice any changes. Am I misunderstanding the states? Or is there some other limitation I don't understand?

**Comment by danburzo** [comment]
Hi @zfox23, re-reading this thread now and not quite remembering the original circumstances for logging this issue, I’m not sure what led me to conclude that <q>Jost-VF uses three states: 0, 1, and 2.</q> The original font, [as seen here](https://indestructibletype.com/Jost.html), does have an `ital` axis that spans the range [0-2], but the version used in the MDN example indeed only spans the range [0-1]. `font-variation-settings: 'ital' 0.5` should look different from `font-variation-settings: 'ital' 1`.

Sorry for sowing more confusion!

With fresh eyes, the thing that needs changing is the phrase:

> The Italic (ital) axis works differently in that it is either on or off; there is no in-between.

There _is_ an in-between. The OpenType specification states that the value has the range [0-1], not just the values 0 and 1. https://learn.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_ital

**Comment by zfox23** [comment]
That's super helpful! Thanks for the quick followup. I'll make that change tomorrow. I'm always glad to learn about typography.
